# These are supported funding model platforms

github: sozonome
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: sozonome
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sozonome
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://buymeacoff.ee/sozonome', 'https://www.nihbuatjajan.com/sozonome', 'https://trakteer.id/sozonome/tip?utm_source=github_sozonome', 'https://saweria.co/sozonome']
